# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTC_test-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTC_test-desktop

end

target 'iTC_test-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTC_test-mobile

end
